version: "3.8"

services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "16-bullseye"

    init: true

    volumes:
      - ..:/workspace:cached
      - //var/run/docker.sock:/var/run/docker.sock
      - nodemodules:/workspace/node_modules:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: node
    ports:
      - "3005:3005"

volumes:
  nodemodules: null